name: Deploy from dev repository
on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  GITHUB_NAME: github-actions[bot]
  GITHUB_MAIL: 41898282+github-actions[bot]@users.noreply.github.com

permissions: write-all

jobs:
  deploy-prod:
    name: deploy-prod
    runs-on: ubuntu-22.04
      # statuses: write
    steps:
      - name: Checkout dev repository
        uses: actions/checkout@v4
        with:
          path: dev
      - name: Checkout prod repository
        run: |
          git clone https://github.com/utcarnivaldayo/actions-prac-prod.git prod
          cd prod
          git remote set-url origin "https://${{secrets.GITHUB_TOKEN}}@github.com/utcarnivaldayo/actions-prac-prod.git"
          git remote -v
          git fetch --prune
          git pull
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
      - name: Install node modules
        run: |
          pwd && ls -la
          cd ${GITHUB_WORKSPACE}/dev
          pwd && ls -la
          test ! -e package-lock.json && echo "Error: package-lock.json does not exist." && exit 1
          npm ci
      - name: Build react
        run: |
          pwd && ls -la
          cd ${GITHUB_WORKSPACE}/dev
          pwd && ls -la
          npm run build
      - name: Copy build artifacts
        run: |
          cp -pr ${GITHUB_WORKSPACE}/dev/dist/* ${GITHUB_WORKSPACE}/prod/
          cd ${GITHUB_WORKSPACE}/prod
          pwd && ls -la
      - name: Commit and push to prod repository
        run: |
          cd ${GITHUB_WORKSPACE}/prod
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git config --local user.email "${{ env.GITHUB_MAIL }}"
          git add .
          git commit -m "generated"
          git push -u origin main
# - name: Commit and push to prod repository
# git remote set-url origin "https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/utcarnivaldayo/actions-prac-prod"