name: Deploy from dev repository
on:
  push:
    tags:
      - v*
  workflow_dispatch:


jobs:
  deploy-prod:
    name: deploy-prod
    runs-on: ubuntu-22.04
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
      - name: Checkout dev repository
        uses: actions/checkout@v4
        with:
          path: dev
      - name: Checkout prod repository
        uses: actions/checkout@v4
        with:
          repository: utcarnivaldayo/actions-prac-prod
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: prod
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
      - name: Install node modules
        run: |
          pwd && ls -la
          cd ${GITHUB_WORKSPACE}/dev
          pwd && ls -la
          test ! -e package-lock.json && echo "Error: package-lock.json does not exist." && exit 1
          npm ci
      - name: Build react
        run: |
          pwd && ls -la
          cd ${GITHUB_WORKSPACE}/dev
          pwd && ls -la
          npm run build
#      - name: Update repository
#        run: |
#          set -x
#          cd ${GITHUB_WORKSPACE}/prod
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git pull
#          git branch
#          git remote -v
      - name: Copy build artifacts
        run: |
          cp -pr ${GITHUB_WORKSPACE}/dev/dist/* ${GITHUB_WORKSPACE}/prod/
          cd ${GITHUB_WORKSPACE}/prod
          pwd && ls -la
      - name: Commit and push to prod repository
        run: |
            set -x
            git remote -v
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "generated"
            git status
            git push


