name: Deploy from dev repository
on:
  push:
    tags:
      - v*
  workflow_dispatch:


jobs:
  deploy-prod:
    name: deploy-prod
    runs-on: ubuntu-22.04
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
      - name: Checkout dev repository
        uses: actions/checkout@v4
        with:
          path: dev
      - name: Checkout prod repository
        uses: actions/checkout@v4
        with:
          repository: utcarnivaldayo/actions-prac-prod
          path: prod
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
      - name: Install node modules
        run: |
          pwd && ls -la
          cd ${GITHUB_WORKSPACE}/dev
          pwd && ls -la
          test ! -e package-lock.json && echo "Error: package-lock.json does not exist." && exit 1
          npm ci
      - name: Build react
        run: |
          pwd && ls -la
          cd ${GITHUB_WORKSPACE}/dev
          pwd && ls -la
          npm run build
      - name: Update repository
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          set -x
          cd ${GITHUB_WORKSPACE}/prod
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --global url."https://x-access-token:${TOKEN}@github.com/".insteadOf "https://github.com/"
          git branch --set-upstream-to=origin/master
          git pull
          git branch
          git remote -v
      - name: Copy build artifacts
        run: |
          cp -pr ${GITHUB_WORKSPACE}/dev/dist/* ${GITHUB_WORKSPACE}/prod/
          cd ${GITHUB_WORKSPACE}/prod
          pwd && ls -la
      - name: Commit and push to prod repository
        run: |
          set -x
          cd ${GITHUB_WORKSPACE}/prod
          git add .
          git commit --author=. -m 'generated'
          git push -u origin master


