name: Deploy from dev repository with volta
on:
  push:
    tags:
      - v*
  workflow_dispatch:
    # NOTE: inputsのデフォルト値を変更した場合はenvのデフォルト値も変更すること
    inputs:
      NODE_VERSIOIN:
        type: string
        description: 'node version'
        required: true
        default: 20.10.0
      DRY_RUN:
        type: boolean
        description: 'dry run'
        required: true
        default: true

env:
  BOT_GITHUB_NAME: github-actions[bot]
  BOT_GITHUB_MAIL: 41898282+github-actions[bot]@users.noreply.github.com
  REMOTE_DEV_REPOSITORY: utcarnivaldayo/actions-prac-dev
  REMOTE_PROD_REPOSITORY: utcarnivaldayo/actions-prac-prod
  LOCAL_DEV_REPOSITORY: dev
  LOCAL_PROD_REPOSITORY: prod
  # 作成したPERSONAL_ACCESS_TOKENの格納場所
  ## Settings -> Screts and variavbles -> Actions -> Repository secrets -> New repository secret
  PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  # NOTE: envのデフォルト値を変更した場合はinputsのデフォルト値も変更すること
  NODE_VERSIOIN: ${{ inputs.NODE_VERSIOIN || '20.10.0' }}
  DRY_RUN: ${{ inputs.DRY_RUN || false }}

jobs:
  deploy-prod:
    name: deploy-prod
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout ${{ env.LOCAL_DEV_REPOSITORY }} repository
        run: git clone -b main --single-branch --depth=1 https://${{ env.PAT }}@github.com/${{ env.REMOTE_DEV_REPOSITORY }}.git ${{ env.LOCAL_DEV_REPOSITORY }}
        shell: bash
      - name: Checkout ${{ env.LOCAL_PROD_REPOSITORY}} repository
        run: |
          git clone -b main --single-branch https://${{ env.PAT }}@github.com/${{ env.REMOTE_PROD_REPOSITORY }}.git ${{ env.LOCAL_PROD_REPOSITORY }}
          cd ${{ env.LOCAL_PROD_REPOSITORY }}
          git clean -fdx && test $(git ls-files | wc -l) -eq 0 || git rm -rf .
        shell: bash
      - name: Install node with volta
        run: |
          node -v
          npm -v
          rm -f $(which node)
          rm -f $(which npm)
          curl https://get.volta.sh | bash
        shell: bash
      - name: Install node modules
        run: |
          set -x
          cd ${{ env.LOCAL_DEV_REPOSITORY }}
          pwd && ls -la
          jq -V
          ${HOME}/.volta/bin/volta install node@$(jq -r .volta.node package.json)
          test ! -e package-lock.json && echo "Error: package-lock.json does not exist." && exit 1
          ${HOME}/.volta/bin/volta which node
          ${HOME}/.volta/bin/volta which npm
          ${HOME}/.volta/bin/volta run --bundled-npm npm ci
          ${HOME}/.volta/bin/volta run node -v
          ${HOME}/.volta/bin/volta run --bundled-npm npm -v
        shell: bash
      - name: Build react
        run: |
          cd ${{ env.LOCAL_DEV_REPOSITORY }}
          pwd && ls -la
          npm run build
      - name: Copy build artifacts
        run: |
          cp -pr ${{ env.LOCAL_DEV_REPOSITORY }}/dist/* ${{ env.LOCAL_PROD_REPOSITORY }}/
          cd ${{ env.LOCAL_PROD_REPOSITORY }}
          pwd && ls -la
      - name: Commit and push to ${{ env.LOCAL_PROD_REPOSITORY }} repository
        run: |
          cd ${{ env.LOCAL_PROD_REPOSITORY }}
          git config --local user.name "${{ env.BOT_GITHUB_NAME }}"
          git config --local user.email "${{ env.BOT_GITHUB_MAIL }}"
          git add .
          git commit -m "generated"
          if [ ${{env.DRY_RUN}} = 'false' ]; then
            git push -u origin main
          else
            echo '===== dry run ====='
            git push -n -u origin main
          fi
