name: Deploy from dev repository
on:
  push:
    tags:
      - v*
  workflow_dispatch:
    # NOTE: inputsのデフォルト値を変更した場合はenvのデフォルト値も変更すること
    inputs:
      NODE_VERSIOIN:
        type: string
        description: 'node version'
        required: true
        default: 20.10.0
      DRY_RUN:
        type: boolean
        description: 'dry run'
        required: true
        default: true

env:
  GITHUB_NAME: github-actions[bot]
  GITHUB_MAIL: 41898282+github-actions[bot]@users.noreply.github.com
  REMOTE_DEV_REPOSITORY: utcarnivaldayo/actions-prac-dev
  REMOTE_PROD_REPOSITORY: utcarnivaldayo/actions-prac-prod
  LOCAL_DEV_REPOSITORY: dev
  LOCAL_PROD_REPOSITORY: prod
  # 作成したPERSONAL_ACCESS_TOKENの格納場所
  ## Settings -> Screts and variavbles -> Actions -> Repository secrets -> New repository secret
  PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  # NOTE: envのデフォルト値を変更した場合はinputsのデフォルト値も変更すること
  NODE_VERSIOIN: ${{ inputs.NODE_VERSIOIN || '20.10.0' }}
  DRY_RUN: ${{ inputs.DRY_RUN || false }}

jobs:
  deploy-prod:
    name: deploy-prod
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout ${{ env.LOCAL_DEV_REPOSITORY }} repository
        run: git clone -b main --single-branch --depth=1 https://${{ env.PAT }}@github.com/${{ env.REMOTE_DEV_REPOSITORY }}.git ${{ env.LOCAL_DEV_REPOSITORY }}
      - name: Checkout ${{ env.LOCAL_PROD_REPOSITORY}} repository
        run: git clone -b main --single-branch https://${{ env.PAT }}@github.com/${{ env.REMOTE_PROD_REPOSITORY }}.git ${{ env.LOCAL_PROD_REPOSITORY }}
      - name: Install node
        run: |
          sudo apt -y update
          sudo apt --no-install-recommends -y install nodejs npm
          sudo npm install n -g
          sudo n --lts
          sudo n ${{env.NODE_VERSIOIN}}
          sudo npm update npm -g
          sudo apt purge nodejs npm
      - name: Install node modules
        run: |
          cd ${{ env.LOCAL_DEV_REPOSITORY }}
          pwd && ls -la
          test ! -e package-lock.json && echo "Error: package-lock.json does not exist." && exit 1
          npm ci
      - name: Build react
        run: |
          cd ${{ env.LOCAL_DEV_REPOSITORY }}
          pwd && ls -la
          npm run build
      - name: Copy build artifacts
        run: |
          cp -pr ${{ env.LOCAL_DEV_REPOSITORY }}/dist/* ${{ env.LOCAL_PROD_REPOSITORY }}/
          cd ${{ env.LOCAL_PROD_REPOSITORY }}
          pwd && ls -la
      - name: Commit and push to ${{ env.LOCAL_PROD_REPOSITORY }} repository
        run: |
          cd ${{ env.LOCAL_PROD_REPOSITORY }}
          test -z "$(git diff)" && echo "Warning: Already latest build." && exit 0
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git config --local user.email "${{ env.GITHUB_MAIL }}"
          git add .
          git commit -m "generated"
          if [ ${{env.DRY_RUN}} = 'false' ]; then
            echo '===== dry run ===== '
            git push -u origin main
          else
            git push -nu origin main
          fi
