name: Deploy from dev repository
on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  GITHUB_NAME: github-actions[bot]
  GITHUB_MAIL: 41898282+github-actions[bot]@users.noreply.github.com
  REMOTE_DEV_REPOSITORY: utcarnivaldayo/actions-prac-dev
  REMOTE_PROD_REPOSITORY: utcarnivaldayo/actions-prac-prod
  LOCAL_DEV_REPOSITORY: dev
  LOCAL_PROD_REPOSITORY: prod
  NODE_VERSIOIN: 20.10.0

jobs:
  deploy-prod:
    name: deploy-prod
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: Checkout ${{ env.LOCAL_DEV_REPOSITORY }} repository
        run: git clone -b main --single-branch --depth=1 https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ env.REMOTE_DEV_REPOSITORY }}.git ${{ env.LOCAL_DEV_REPOSITORY }}
      - name: Checkout ${{ env.LOCAL_PROD_REPOSITORY}} repository
        run: git clone -b main --single-branch https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ env.REMOTE_PROD_REPOSITORY }}.git ${{ env.LOCAL_PROD_REPOSITORY }}
      - name: Install node
        run: |
          sudo apt -y update
          sudo apt --no-install-recommends -y install nodejs npm
          sudo apt --no-install-recommends -y install n -g
          sudo npm update npm -g
          sudo apt purge nodejs npm
          sudp n --lts
          sudo n ${{env.NODE_VERSIOIN}}
      - name: Install node modules
        run: |
          cd ${{ env.LOCAL_DEV_REPOSITORY }}
          pwd && ls -la
          test ! -e package-lock.json && echo "Error: package-lock.json does not exist." && exit 1
          npm ci
      - name: Build react
        run: |
          cd ${{ env.LOCAL_DEV_REPOSITORY }}
          pwd && ls -la
          npm run build
      - name: Copy build artifacts
        run: |
          cp -pr ${{ env.LOCAL_DEV_REPOSITORY }}/dist/* ${{ env.LOCAL_PROD_REPOSITORY }}/
          cd ${{ env.LOCAL_PROD_REPOSITORY }}
          pwd && ls -la
      - name: Commit and push to ${{ env.LOCAL_PROD_REPOSITORY }} repository
        run: |
          cd ${{ env.LOCAL_PROD_REPOSITORY }}
          test -z "$(git diff)" && echo "Already latest." && exit 0
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git config --local user.email "${{ env.GITHUB_MAIL }}"
          git add .
          git commit -m "generated"
          git push -u origin main
