name: Hello, World!
on:
    push:
        tags:
            - v*
    workflow_dispatch:

jobs:
    build:
        name: build-a
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello, World!"