name: Hello, World!
on:
    push:
        tags:
            - v*
    workflow_dispatch:

jobs:
    deploy-prod:
        name: deploy-prod
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                path: main
            - run: ls && cd main && ls