name: Deploy from dev repository
on:
    push:
        tags:
            - v*
    workflow_dispatch:

jobs:
    deploy-prod:
        name: deploy-prod
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout prod repository
              uses: actions/checkout@v4
              with:
                path: actions-prac-dev
            - name: Checkout dev repository
              uses: actions/checkout@v4
              with:
                repository: utcarnivaldayo/actions-prac-prod
                path: actions-prac-prod
            - name: install node
              uses: actions/setup-node@v4
              with:
                node-version: 20.10.0
            - run: |
                cd actions-prac-dev
                node -v
                npm ci
                npm run build
                ls
